export const SET_MESSAGES = "SET_MESSAGES";

export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const SET_TRANSACTION_ID = "SET_TRANSACTION_ID";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const UPDATE_TRANSACTIONS_FILTERS = "UPDATE_TRANSACTIONS_FILTERS";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_MONEY_RANGE = "SET_MONEY_RANGE";
export const SET_SEARCH = "SET_SEARCH";
export const REMOVE_TRANSACTIONS = "REMOVE_TRANSACTIONS";
export const SET_TRANSACTIONS_LOADED = "SET_TRANSACTIONS_LOADED";
export const SET_TRANSACTIONS_NOT_LOADED = "SET_TRANSACTIONS_NOT_LOADED";

export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";
export const SET_USER_LOADED = "SET_USER_LOADED";

export const SET_WALLETS = "SET_WALLETS";
export const ADD_WALLET = "ADD_WALLET";
export const SET_CURRENT_WALLET = "SET_CURRENT_WALLET";
export const REMOVE_WALLETS = "REMOVE_WALLETS";
export const SET_WALLETS_LOADED = "SET_WALLETS_LOADED";
export const SET_WALLETS_NOT_LOADED = "SET_WALLETS_NOT_LOADED";
